### ISSUE TITLE
MatrixMultiply issue

### ISSUE THREAD

**Issue by AminSahebi** [szuckerm/DARTS#2]
Dear sir,

Many thanks for a great job, I'm interested to run a MatrixMultiplication that is located in the repository,
However, when I try to execute some examples in **matrixmultiplicationTime.sh** file, I receive the following error, I really appreciate it if you please shed a light on this and help me to solve it. 

"Requested 32 only 4 available."

Thanks
Amin

**Comment by szuckerm** [comment]
Dear Amin, 

If you look at the source code of the script file, you can see lines like : 

`./mmTime 2 15 2 1 33554432 32 32 >> mmTimeStatic.txt`

In mmTime.cpp, in the `main` function, you can see that the first two parameters are called `tps` and `cds`: they are used to say how many TP schedulers and how many codelet schedulers per TP scheduler should be allocated. In the line above, we wrote `2` and `15`, which implies the use of 30 hardware threads/cores to run the whole computation (technically, 2 additional HW threads are required, hence we need 32 cores in total here). If your machine does not have that many HW computation units, the program will fail with the error message you found. I suggest you try to change the first 2 parameters with, say, `1` and `1` at first, and see what happens.

**Comment by AminSahebi** [comment]
Thanks for your quick reply,
I got the point, however, I tried with the smaller numbers for example as you said **1**, but I faced core dump. I tried to debug to see if there are any arrays or allocations which go uninitialized or returning NULL but no success.
I will try to see if I could extract more debug information that can help me to find where is the problem,

Thanks
